language: cpp
dist: bionic
compiler: gcc
os: 
  - linux
  - # osx
  - # windows
git:
  quiet: true

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: travis_qmake_gcc_cpp17_deploy
  skip_cleanup: true
  on:
    tags: true

script: 
  - qmake
  - make --silent
  - ./travis_qmake_gcc_cpp17_deploy
